# Pandas & Plotly — analyser les ventes d'une boutique en ligne

---
# Partie 1 — Importer et découvrir les données

**Aide-mémoire**

| Besoin | Code |
|---|---|
| Lire un CSV | `pd.read_csv("fichier.csv")` |
| Lire un CSV en convertissant une colonne en date | `pd.read_csv("fichier.csv", parse_dates=["colonne"])` |
| Premières / dernières lignes | `df.head()`, `df.tail(3)` |
| Lignes au hasard | `df.sample(5)` |
| Dimensions | `df.shape` |
| Types et valeurs non nulles | `df.info()`, `df.dtypes` |
| Valeurs manquantes | `df.isna().sum()` |

### Exercice 1.1 — Importer

Importe pandas sous l'alias `pd`, puis charge le fichier dans un DataFrame nommé `df`, en demandant à pandas de lire `date_commande` comme une date.

In [1]:
from pathlib import Path
import pandas as pd

In [2]:
search = Path.home() / "PERSO"

filepath = list(search.rglob("commandes_ecommerce.csv"))[0]
if filepath.exists():
    df = pd.read_csv(filepath, parse_dates=["date_commande"])

### Exercice 1.2 — Premier coup d'œil

Affiche les 5 premières lignes, puis (dans la cellule suivante) 8 lignes prises au hasard.

In [3]:
df.head()

,commande_id,date_commande,client_id,age_client,ville,canal,categorie,prix_unitaire,quantite,remise_pct,mode_paiement,delai_livraison_jours,note_client,retour
0,CMD-00001,2025-01-01,C285,24,Bordeaux,Magasin,Mode,43.36,1,10,Carte bancaire,NaN,NaN,False
1,CMD-00002,2025-01-01,C194,57,Lille,Site web,Sport,44.41,2,10,Carte bancaire,4.0,5.0,False
2,CMD-00003,2025-01-01,C166,26,Toulouse,Application mobile,Mode,27.33,1,10,Carte bancaire,4.0,4.0,False
3,CMD-00004,2025-01-02,C213,38,Paris,Site web,Électronique,113.62,1,30,Carte bancaire,7.0,4.0,False
4,CMD-00005,2025-01-02,C215,34,Strasbourg,Site web,Maison,61.00,2,20,Carte cadeau,2.0,NaN,False

In [4]:
df.sample(8)

,commande_id,date_commande,client_id,age_client,ville,canal,categorie,prix_unitaire,quantite,remise_pct,mode_paiement,delai_livraison_jours,note_client,retour
64,CMD-00065,2025-01-22,C155,37,Toulouse,Site web,Beauté,33.10,1,0,Carte bancaire,3.0,5.0,False
410,CMD-00411,2025-06-20,C152,25,Lyon,Site web,Sport,12.64,2,0,Carte bancaire,3.0,5.0,False
960,CMD-00961,2025-12-23,C019,49,Bordeaux,Application mobile,Maison,221.68,2,10,Carte bancaire,3.0,5.0,False
97,CMD-00098,2025-01-31,C155,37,Toulouse,Magasin,Mode,46.54,2,30,Carte bancaire,NaN,5.0,False
908,CMD-00909,2025-12-13,C227,71,Paris,Site web,Électronique,116.05,2,5,Carte bancaire,7.0,3.0,False
236,CMD-00237,2025-04-04,C014,53,Toulouse,Site web,Électronique,140.22,2,0,Carte bancaire,4.0,5.0,False
765,CMD-00766,2025-11-06,C255,35,Lille,Application mobile,Électronique,220.27,1,0,Carte cadeau,4.0,NaN,False
545,CMD-00546,2025-08-15,C120,35,Lille,Application mobile,Beauté,25.79,3,0,Carte bancaire,3.0,NaN,False

### Exercice 1.3 — Les dimensions

Combien de lignes et de colonnes contient le tableau ?

In [5]:
df.shape

(1000, 14)

### Exercice 1.4 — Les types

Affiche le type de chaque colonne. Vérifie que `date_commande` est bien une date (`datetime64`) et non du texte.

In [6]:
df.dtypes

commande_id                         str
date_commande            datetime64[us]
client_id                           str
age_client                        int64
ville                               str
canal                               str
categorie                           str
prix_unitaire                   float64
quantite                          int64
remise_pct                        int64
mode_paiement                       str
delai_livraison_jours           float64
note_client                     float64
retour                             bool
dtype: object

### Exercice 1.5 — Les valeurs manquantes

Compte les valeurs manquantes de chaque colonne.

In [7]:
df.isna().sum()

commande_id                0
date_commande              0
client_id                  0
age_client                 0
ville                      0
canal                      0
categorie                  0
prix_unitaire              0
quantite                   0
remise_pct                 0
mode_paiement              0
delai_livraison_jours    217
note_client               84
retour                     0
dtype: int64

---
# Partie 2 — Résumer les données

**Aide-mémoire**

| Besoin | Code |
|---|---|
| Statistiques de toutes les colonnes numériques | `df.describe()` |
| Une statistique sur une colonne | `df["col"].mean()`, `.median()`, `.min()`, `.max()`, `.sum()` |
| Compter chaque modalité | `df["col"].value_counts()` |
| …en proportions | `df["col"].value_counts(normalize=True)` |
| Valeurs distinctes | `df["col"].unique()`, `df["col"].nunique()` |

### Exercice 2.1 — `describe`

Affiche les statistiques descriptives des colonnes numériques. Lis le tableau et réponds mentalement :

- Quel est l'âge moyen des clients ? Le plus jeune, le plus âgé ?
- Le prix unitaire moyen est-il proche du prix médian (ligne `50%`) ? Qu'est-ce que cela dit de la distribution des prix ?

In [8]:
average_age = df.describe().loc["mean", "age_client"]
min_age = df.describe().loc["min", "age_client"]
max_age = df.describe().loc["max", "age_client"]

print(f"average is {average_age.item()}")
print(f"min is {min_age.item()}")
print(f"max is {max_age.item()}")

average is 38.429
min is 18.0
max is 75.0

In [9]:
median_price = df.describe().loc["50%", "prix_unitaire"]
average_price = df.describe().loc["mean", "prix_unitaire"]

print(f"min is {median_price.item()}")
print(f"max is {average_price.item()}")

min is 52.845
max is 95.59000999999999

### Exercice 2.2 — Une statistique à la fois

Affiche le prix unitaire moyen, médian et maximum, chacun arrondi à 2 décimales.

In [10]:
print(round(df["prix_unitaire"].mean().item(), 2))
print(round(df["prix_unitaire"].median().item(), 2))
print(round(df["prix_unitaire"].max().item(), 2))

95.59
52.84
1366.95

### Exercice 2.3 — Répartition par catégorie

Combien de commandes dans chaque catégorie ? Affiche ensuite la même chose en pourcentage du total.

In [11]:
df["categorie"].value_counts()

categorie
Mode            287
Électronique    188
Maison          187
Sport           129
Beauté          128
Livres           81
Name: count, dtype: int64

In [12]:
df["categorie"].value_counts(normalize=True)

categorie
Mode            0.287
Électronique    0.188
Maison          0.187
Sport           0.129
Beauté          0.128
Livres          0.081
Name: proportion, dtype: float64

### Exercice 2.4 — Clients et villes

Combien de clients différents ont passé commande ? Quelles sont les villes présentes ?

In [13]:
df["client_id"].nunique()

239

In [14]:
df["ville"].nunique()

8

In [15]:
list(df["ville"].unique())

['Bordeaux',
 'Lille',
 'Toulouse',
 'Paris',
 'Strasbourg',
 'Nantes',
 'Lyon',
 'Marseille']

### Exercice 2.5 — `describe` sur du texte

`describe` fonctionne aussi sur une colonne de texte, mais renvoie d'autres informations. Essaie sur la colonne `canal` : que signifient `unique`, `top` et `freq` ?

In [16]:
df["canal"].describe()

count         1000
unique           3
top       Site web
freq           455
Name: canal, dtype: object

---
# Partie 3 — Filtrer avec des masques

Un **masque** est une série de `True` / `False`, une valeur par ligne. Placé entre crochets, il ne garde que les lignes à `True`.

```python
masque = df["age_client"] >= 60     # une série de booléens
df[masque]                          # les lignes où c'est True
masque.sum()                        # le nombre de True (True compte pour 1)
```

**Aide-mémoire**

| Besoin | Code |
|---|---|
| ET | `(cond1) & (cond2)` |
| OU | `(cond1) \| (cond2)` |
| NON | `~cond` |
| Appartenance à une liste | `df["col"].isin(["a", "b"])` |
| Entre deux bornes (incluses) | `df["col"].between(10, 20)` |
| Valeur manquante / présente | `df["col"].isna()`, `df["col"].notna()` |
| Texte | `df["col"].str.startswith("L")`, `df["col"].str.contains("web")` |
| Lignes + colonnes | `df.loc[masque, ["col1", "col2"]]` |

Avec pandas on écrit `&` et `|` (pas `and` / `or`), et chaque condition doit être **entre parenthèses**.

### Exercice 3.1 — Sélectionner des colonnes

Affiche uniquement les colonnes `client_id`, `categorie` et `prix_unitaire` des 5 premières lignes.

In [17]:
df.loc[:5, ["client_id", "categorie", "prix_unitaire"]]

  client_id     categorie  prix_unitaire
0      C285          Mode          43.36
1      C194         Sport          44.41
2      C166          Mode          27.33
3      C213  Électronique         113.62
4      C215        Maison          61.00
5      C178         Sport          51.35

### Exercice 3.2 — Un masque simple

Crée un masque `masque_paris` pour les commandes de clients parisiens. Affiche les premières lignes filtrées, puis le nombre de commandes concernées.

In [18]:
masque_paris = df["ville"] == "Paris"
display(df[masque_paris].shape[0])
df[masque_paris].head()

207

,commande_id,date_commande,client_id,age_client,ville,canal,categorie,prix_unitaire,quantite,remise_pct,mode_paiement,delai_livraison_jours,note_client,retour
3,CMD-00004,2025-01-02,C213,38,Paris,Site web,Électronique,113.62,1,30,Carte bancaire,7.0,4.0,False
6,CMD-00007,2025-01-02,C080,34,Paris,Application mobile,Maison,100.58,2,20,PayPal,7.0,NaN,False
11,CMD-00012,2025-01-04,C020,37,Paris,Magasin,Mode,40.98,1,0,Carte cadeau,NaN,4.0,False
21,CMD-00022,2025-01-08,C038,27,Paris,Application mobile,Beauté,23.81,2,0,Carte cadeau,3.0,5.0,False
25,CMD-00026,2025-01-10,C249,75,Paris,Site web,Mode,46.12,1,20,Virement,2.0,5.0,False

### Exercice 3.3 — Les articles chers

Combien de commandes portent sur un article dont le prix unitaire dépasse 500 € ? De quelles catégories s'agit-il ?

In [19]:
masque_cher = df["prix_unitaire"] > 500
list(df[masque_cher]["categorie"].unique())

['Électronique']

### Exercice 3.4 — Deux conditions (ET)

Trouve les commandes de la catégorie `Mode` ayant bénéficié d'une remise d'au moins 20 %.

In [23]:
masque_mode = df["categorie"] == "Mode"
masque_remise = df["remise_pct"] >= 20
df[masque_mode & masque_remise].head()

,commande_id,date_commande,client_id,age_client,ville,canal,categorie,prix_unitaire,quantite,remise_pct,mode_paiement,delai_livraison_jours,note_client,retour
10,CMD-00011,2025-01-04,C015,44,Lille,Site web,Mode,53.43,1,20,Carte bancaire,5.0,5.0,False
25,CMD-00026,2025-01-10,C249,75,Paris,Site web,Mode,46.12,1,20,Virement,2.0,5.0,False
51,CMD-00052,2025-01-18,C153,18,Toulouse,Application mobile,Mode,28.35,1,30,Carte bancaire,4.0,3.0,False
66,CMD-00067,2025-01-22,C183,33,Lille,Site web,Mode,79.76,1,20,Carte bancaire,6.0,NaN,False
73,CMD-00074,2025-01-24,C040,46,Paris,Site web,Mode,18.59,1,20,PayPal,2.0,3.0,True

### Exercice 3.5 — OU, puis `isin`

Compte les commandes des clients de Lyon **ou** de Marseille, de deux façons : avec `|`, puis avec `isin`.

In [24]:
masque_lyon = df["ville"] == "Lyon"
masque_marseille = df["ville"] == "Marseille"

df[masque_lyon | masque_marseille]

,commande_id,date_commande,client_id,age_client,ville,canal,categorie,prix_unitaire,quantite,remise_pct,mode_paiement,delai_livraison_jours,note_client,retour
9,CMD-00010,2025-01-03,C089,44,Lyon,Magasin,Électronique,143.11,1,0,PayPal,NaN,5.0,False
14,CMD-00015,2025-01-05,C246,21,Marseille,Site web,Électronique,73.71,1,20,Carte bancaire,4.0,3.0,False
24,CMD-00025,2025-01-09,C268,43,Lyon,Application mobile,Sport,107.15,4,0,PayPal,4.0,NaN,False
39,CMD-00040,2025-01-15,C072,23,Marseille,Application mobile,Maison,145.01,1,0,Carte bancaire,3.0,4.0,False
43,CMD-00044,2025-01-16,C289,34,Marseille,Site web,Beauté,35.02,1,20,PayPal,3.0,4.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,CMD-00982,2025-12-29,C202,56,Lyon,Magasin,Maison,67.21,1,0,Carte cadeau,NaN,3.0,False
982,CMD-00983,2025-12-29,C072,23,Marseille,Site web,Beauté,20.43,4,10,Carte bancaire,8.0,NaN,False
983,CMD-00984,2025-12-29,C218,55,Lyon,Application mobile,Beauté,38.93,3,0,PayPal,3.0,5.0,False
984,CMD-00985,2025-12-29,C202,56,Lyon,Site web,Livres,14.07,1,0,Carte bancaire,6.0,4.0,False
989,CMD-00990,2025-12-30,C248,62,Marseille,Magasin,Sport,29.50,1,5,Carte bancaire,NaN,3.0,False

In [25]:
df[df["ville"].isin(["Lyon", "Marseille"])].head()

,commande_id,date_commande,client_id,age_client,ville,canal,categorie,prix_unitaire,quantite,remise_pct,mode_paiement,delai_livraison_jours,note_client,retour
9,CMD-00010,2025-01-03,C089,44,Lyon,Magasin,Électronique,143.11,1,0,PayPal,NaN,5.0,False
14,CMD-00015,2025-01-05,C246,21,Marseille,Site web,Électronique,73.71,1,20,Carte bancaire,4.0,3.0,False
24,CMD-00025,2025-01-09,C268,43,Lyon,Application mobile,Sport,107.15,4,0,PayPal,4.0,NaN,False
39,CMD-00040,2025-01-15,C072,23,Marseille,Application mobile,Maison,145.01,1,0,Carte bancaire,3.0,4.0,False
43,CMD-00044,2025-01-16,C289,34,Marseille,Site web,Beauté,35.02,1,20,PayPal,3.0,4.0,False

### Exercice 3.6 — `between`

Combien de commandes ont été passées par des clients de 25 à 35 ans inclus ?

In [26]:
df[df["age_client"].between(25, 35)].head()

,commande_id,date_commande,client_id,age_client,ville,canal,categorie,prix_unitaire,quantite,remise_pct,mode_paiement,delai_livraison_jours,note_client,retour
2,CMD-00003,2025-01-01,C166,26,Toulouse,Application mobile,Mode,27.33,1,10,Carte bancaire,4.0,4.0,False
4,CMD-00005,2025-01-02,C215,34,Strasbourg,Site web,Maison,61.00,2,20,Carte cadeau,2.0,NaN,False
6,CMD-00007,2025-01-02,C080,34,Paris,Application mobile,Maison,100.58,2,20,PayPal,7.0,NaN,False
16,CMD-00017,2025-01-06,C209,27,Nantes,Site web,Maison,104.22,2,10,PayPal,4.0,5.0,False
18,CMD-00019,2025-01-06,C121,25,Bordeaux,Application mobile,Mode,40.79,3,0,Carte bancaire,4.0,4.0,False

In [27]:
df[df["age_client"].between(25, 35)].shape[0]

309

### Exercice 3.7 — La négation

Combien de commandes n'ont **pas** été payées par `Carte bancaire` ? Utilise `~`.

In [28]:
df[~(df["mode_paiement"] == "Carte bancaire")].head()

,commande_id,date_commande,client_id,age_client,ville,canal,categorie,prix_unitaire,quantite,remise_pct,mode_paiement,delai_livraison_jours,note_client,retour
4,CMD-00005,2025-01-02,C215,34,Strasbourg,Site web,Maison,61.00,2,20,Carte cadeau,2.0,NaN,False
5,CMD-00006,2025-01-02,C178,40,Toulouse,Magasin,Sport,51.35,2,0,Carte cadeau,NaN,5.0,False
6,CMD-00007,2025-01-02,C080,34,Paris,Application mobile,Maison,100.58,2,20,PayPal,7.0,NaN,False
8,CMD-00009,2025-01-03,C297,42,Bordeaux,Application mobile,Maison,98.11,2,10,Carte cadeau,2.0,5.0,False
9,CMD-00010,2025-01-03,C089,44,Lyon,Magasin,Électronique,143.11,1,0,PayPal,NaN,5.0,False

In [29]:
df[~(df["mode_paiement"] == "Carte bancaire")].shape[0]

425

### Exercice 3.8 — Enquête sur les valeurs manquantes

En partie 1, on a vu que `delai_livraison_jours` contient des valeurs manquantes. Est-ce une erreur dans les données ?

1. Filtre les lignes où le délai est manquant.
2. Regarde la répartition de leur `canal`.
3. Conclus.

In [30]:
list(df[df["delai_livraison_jours"].isna()]["canal"].unique())

['Magasin']

### Exercice 3.9 — `loc` : filtrer des lignes et choisir des colonnes

Affiche, pour les commandes d'`Électronique` qui ont été **retournées**, uniquement les colonnes `commande_id`, `prix_unitaire` et `note_client`.

La colonne `retour` contient déjà des booléens : elle peut servir directement de masque.

In [31]:
df[df["retour"]].loc[:, ["commande_id", "prix_unitaire", "note_client"]].head()

   commande_id  prix_unitaire  note_client
13   CMD-00014          90.69          3.0
17   CMD-00018          25.74          NaN
35   CMD-00036          36.48          5.0
44   CMD-00045         228.15          4.0
46   CMD-00047          84.91          2.0

### Exercice 3.10 — Masque sur du texte

Combien de commandes viennent d'une ville dont le nom commence par `L` ? Lesquelles sont-ce ?

In [32]:
list(df[df["ville"].str.startswith("L")]["ville"].unique())

['Lille', 'Lyon']

---
# Partie 4 — Créer des colonnes, `apply`


**Aide-mémoire**

```python
df["total"] = df["a"] * df["b"]               # calcul entre colonnes (rapide, à privilégier)
df["mois"] = df["date"].dt.month              # extraire une partie d'une date

def ma_fonction(valeur):                      # une fonction qui traite UNE valeur…
    return valeur * 2
df["double"] = df["a"].apply(ma_fonction)     # …appliquée à chaque valeur de la colonne

df["double"] = df["a"].apply(lambda x: x * 2) # la même chose avec une fonction anonyme

def ma_regle(ligne):                          # une fonction qui reçoit UNE LIGNE entière
    return ligne["a"] + ligne["b"]
df["somme"] = df.apply(ma_regle, axis=1)      # axis=1 : on parcourt les lignes
```

`apply` est l'outil à tout faire : il sert quand la règle est trop particulière pour s'écrire comme un simple calcul entre colonnes.

### Exercice 4.1 — Le montant de la commande

Il manque l'information principale : combien chaque commande a rapporté. Crée la colonne `montant` :

> montant = prix unitaire × quantité × (1 − remise / 100), arrondi à 2 décimales (`.round(2)`)

Sans passer par apply 

Affiche ensuite le chiffre d'affaires total.

In [33]:
import numpy as np

In [34]:
df["montant"] = (df["prix_unitaire"]*df["quantite"]*(1 - df["remise_pct"]/100)).round(2)

Fait la même chose en passant par apply et compare les deux temps d'éxécution avec %timeit

In [35]:
df["montant"] = df.apply(lambda x: np.round(x["prix_unitaire"]*x["quantite"]*(1 - x["remise_pct"]/100)), axis=1)

In [36]:
%timeit (df["prix_unitaire"]*df["quantite"]*(1 - df["remise_pct"]/100)).round(2)
%timeit df.apply(lambda x: np.round(x["prix_unitaire"]*x["quantite"]*(1 - x["remise_pct"]/100)), axis=1)

329 μs ± 29.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
14.2 ms ± 333 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

### Exercice 4.2 — Découper la date

Crée deux colonnes à partir de `date_commande` :

- `mois` : le numéro du mois (1 à 12)
- `jour_semaine` : le nom du jour

In [37]:
df["mois"] = df["date_commande"].dt.month
df["jour_semaine"] = df["date_commande"].dt.day_name()

### Exercice 4.3 — `apply` avec une fonction : la tranche d'âge

Écris une fonction `tranche_age(age)` qui renvoie `"18-29"`, `"30-44"`, `"45-59"` ou `"60+"`, puis applique-la à `age_client` pour créer la colonne `tranche_age`.

Vérifie avec `value_counts()`.

In [38]:
def tranche_age(age):
    if age < 30:
        return "18-29"
    elif age < 45:
        return "30-44"
    elif age < 60:
        return "45-59"
    else:
        return "60+"

df["tranche_age"] = df["age_client"].apply(tranche_age)

In [39]:
df["tranche_age"].value_counts()

tranche_age
30-44    490
18-29    253
45-59    210
60+       47
Name: count, dtype: int64

Utilise `pd.cut()` pour faire la même colonne et vérifie la différence de temps de calcul avec %timeit

In [40]:
df["tranche_age"] = pd.cut(df["age_client"], bins=[17, 29, 44, 59, 120], labels=["18-29", "30-44", "45-59", "60+"])

In [41]:
%timeit df["age_client"].apply(tranche_age)
%timeit pd.cut(df["age_client"], bins=[17, 29, 44, 59, 120], labels=["18-29", "30-44", "45-59", "60+"])

265 μs ± 25.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
659 μs ± 20.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

Augmente la taille du jeu de donnée avec la commande suivante : `grand = pd.concat([df] * 1000, ignore_index=True)`
et relance le même timeit avec grand plutôt que df

In [42]:
grand = pd.concat([df] * 1000, ignore_index=True)

In [43]:
%timeit grand["age_client"].apply(tranche_age)
%timeit pd.cut(grand["age_client"], bins=[17, 29, 44, 59, 120], labels=["18-29", "30-44", "45-59", "60+"])

122 ms ± 2.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
14.5 ms ± 444 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Suprime grand avec `del grand` pour libérer de la mémoire.

In [44]:
del grand

### Exercice 4.4 — `apply` avec une `lambda`

Crée la colonne `avec_remise` qui vaut `"Oui"` si `remise_pct` est supérieur à 0, `"Non"` sinon, à l'aide d'une `lambda`.

In [45]:
df["avec_remise"] = df["remise_pct"].apply(lambda x: "Oui" if x > 0 else "Non")

Crée la même colonne avec np.where puis vérifie la différence de performance entre les deux avec %timeit

In [46]:
df["avec_remise"] = np.where(df["remise_pct"] > 0, "Oui", "Non")

In [47]:
%timeit df["remise_pct"].apply(lambda x: "Oui" if x > 0 else "Non")
%timeit np.where(df["remise_pct"] > 0, "Oui", "Non")

253 μs ± 10.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
102 μs ± 13.3 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

### Exercice 4.5 — `apply` ligne par ligne : les frais de livraison

La règle dépend de **deux** colonnes, il faut donc travailler sur la ligne entière (`axis=1`) :

- canal `Magasin` : 0 €
- sinon, montant de 60 € ou plus : 0 € (livraison offerte)
- sinon : 4.90 €

Crée la colonne `frais_livraison` et affiche le total des frais encaissés.

In [48]:
def frais_livraison(ligne):
    if ligne["canal"] == "Magasin":
        return 0.0
    elif ligne["montant"] >= 60:
        return 0.0
    else:
        return 4.90


df["frais_livraison"] = df.apply(frais_livraison, axis=1)

print(f"Total des frais de livraison : {round(df["frais_livraison"].sum(), 2)}€")
df["frais_livraison"].value_counts()

Total des frais de livraison : 1514.1€

frais_livraison
0.0    691
4.9    309
Name: count, dtype: int64

Crée la même colonne avec np.where puis vérifie la différence de performance entre les deux avec %timeit

In [49]:
df["frais_livraison"] = np.where((df["canal"] == "Magasin") | (df["montant"] >= 60), 0.0, 4.90)

In [50]:
%timeit df.apply(frais_livraison, axis=1)
%timeit np.where((df["canal"] == "Magasin") | (df["montant"] >= 60), 0.0, 4.90)

7.91 ms ± 365 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
368 μs ± 15.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

### Exercice 4.6 — `apply` et valeurs manquantes : la satisfaction

Crée la colonne `satisfaction` à partir de `note_client` :

- note manquante → `"Sans avis"`
- note de 4 ou 5 → `"Satisfait"`
- note de 3 → `"Neutre"`
- note de 1 ou 2 → `"Mécontent"`

`pd.isna(valeur)` teste si une valeur est manquante. Fais ce test **en premier** : une comparaison avec une valeur manquante renvoie toujours `False`.

In [51]:
def satisfaction(note):
    if pd.isna(note):
        return "Sans avis"
    elif note >= 4:
        return "Satisfait"
    elif note == 3:
        return "Neutre"
    else:
        return "Mécontent"

df["satisfaction"] = df["note_client"].apply(satisfaction)

df["satisfaction"].value_counts()

satisfaction
Satisfait    760
Neutre       142
Sans avis     84
Mécontent     14
Name: count, dtype: int64

---
# Partie 5 — Agréger avec `groupby`

`groupby` répond à toutes les questions du type « … **par** … » : le chiffre d'affaires *par* catégorie, la note moyenne *par* canal. Il procède en trois temps : **découper** le tableau en groupes, **calculer** quelque chose dans chaque groupe, **rassembler** les résultats.

**Aide-mémoire**

```python
df.groupby("categorie")["montant"].sum()                    # une colonne, un calcul
df.groupby("categorie")["montant"].agg(["sum", "mean"])     # une colonne, plusieurs calculs

df.groupby("categorie").agg(                                # plusieurs colonnes, résultats nommés
    nb_commandes=("commande_id", "count"),
    ca=("montant", "sum"),
)

df.groupby(["categorie", "canal"])["montant"].sum()         # deux niveaux de regroupement
```

Utile ensuite : `.sort_values(ascending=False)` pour trier, `.head(5)` pour un top 5, `.round(2)` pour arrondir, `.reset_index()` pour retrouver un DataFrame classique (indispensable pour Plotly).

### Exercice 5.1 — Le chiffre d'affaires par catégorie

Calcule le chiffre d'affaires (somme des montants) de chaque catégorie, trié du plus grand au plus petit.

In [52]:
df.groupby("categorie")["montant"].sum().sort_values()

categorie
Livres           3012.0
Beauté           6703.0
Sport           12650.0
Mode            23673.0
Maison          24451.0
Électronique    51755.0
Name: montant, dtype: float64

### Exercice 5.2 — Le panier moyen par canal

Quel est le montant moyen d'une commande pour chaque canal ? Arrondis à 2 décimales.

In [53]:
df.groupby("canal")["montant"].mean().round(2)

canal
Application mobile    127.97
Magasin               124.00
Site web              117.28
Name: montant, dtype: float64

### Exercice 5.3 — Plusieurs indicateurs d'un coup

Construis un tableau `synthese` avec, pour chaque catégorie :

- `nb_commandes` : le nombre de commandes
- `ca` : le chiffre d'affaires
- `panier_moyen` : le montant moyen
- `note_moyenne` : la note client moyenne

Trie-le par chiffre d'affaires décroissant.

In [54]:
synthese = df.groupby("categorie").agg(
    nb_commandes=("commande_id", "count"),
    ca=("montant", "sum"),
    panier_moyen=("montant", "mean"),
    note_moyenne=("note_client", "mean")
).sort_values(by="ca", ascending=False)

In [55]:
synthese

              nb_commandes       ca  panier_moyen  note_moyenne
categorie
Électronique           188  51755.0    275.292553      4.287356
Maison                 187  24451.0    130.754011      4.217143
Mode                   287  23673.0     82.484321      4.256705
Sport                  129  12650.0     98.062016      4.208696
Beauté                 128   6703.0     52.367188      4.271186
Livres                  81   3012.0     37.185185      4.301370

### Exercice 5.4 — Deux niveaux : catégorie × canal

Calcule le chiffre d'affaires par catégorie **et** par canal.

Le résultat est une longue série. Ajoute `.unstack()` à la fin pour obtenir un tableau croisé (catégories en lignes, canaux en colonnes).

In [56]:
df.groupby(["categorie", "canal"])["montant"].sum().unstack()

canal         Application mobile  Magasin  Site web
categorie
Beauté                    1924.0   1505.0    3274.0
Livres                     944.0    548.0    1520.0
Maison                    7796.0   4460.0   12195.0
Mode                      8961.0   4740.0    9972.0
Sport                     4156.0   2558.0    5936.0
Électronique             18193.0  13096.0   20466.0

### Exercice 5.5 — La saisonnalité

Calcule, pour chaque mois, le nombre de commandes et le chiffre d'affaires. Quels sont les mois forts et les mois creux ?

In [57]:
df.groupby("mois").agg(
    n_commandes=("commande_id", "count"),
    ca=("montant", "sum")
).sort_values(by="ca")

      n_commandes       ca
mois
2              61   6669.0
8              60   7632.0
5              66   8095.0
6              69   8346.0
3              69   8991.0
7              82  10040.0
4              71  10134.0
1              99  10607.0
10             81  10620.0
9              85  11352.0
11            111  12219.0
12            146  17539.0

### Exercice 5.6 — Le taux de retour par catégorie

Quelle part des commandes est retournée dans chaque catégorie ? Exprime-la en pourcentage, triée par ordre décroissant.

La moyenne d'une colonne de booléens donne directement la proportion de `True`.

In [58]:
df.groupby("categorie")["retour"].mean().sort_values(ascending=False)

categorie
Mode            0.247387
Sport           0.116279
Maison          0.064171
Électronique    0.053191
Livres          0.024691
Beauté          0.007812
Name: retour, dtype: float64

### Exercice 5.7 — Les meilleurs clients

Affiche les 5 clients qui ont le plus dépensé sur l'année, avec leur nombre de commandes et leur dépense totale.

In [59]:
df.groupby("client_id").agg(
    sum=("montant", "sum"),
    number=("commande_id", "count")
).sort_values(by="sum", ascending=False)[:5]

              sum  number
client_id
C020       3013.0      18
C178       2868.0      11
C194       2248.0      10
C293       2154.0      16
C279       2119.0      20

### Exercice 5.8 — Délai de livraison et satisfaction

Calcule, pour chaque délai de livraison, le nombre de commandes et la note moyenne. Que constates-tu ?

Méfie-toi des moyennes calculées sur très peu de commandes.

In [60]:
df.groupby("delai_livraison_jours").agg(
    num_commande=("commande_id", "count"),
    note_moyenne=("note_client", "mean")
).sort_index()

                       num_commande  note_moyenne
delai_livraison_jours
2.0                             143      4.644928
3.0                             250      4.409692
4.0                             185      4.222892
5.0                             111      4.037383
6.0                              55      3.700000
7.0                              29      3.555556
8.0                               8      2.600000
9.0                               1      1.000000
10.0                              1      4.000000

---
# Partie 6 — Visualiser avec Plotly

Plotly Express crée un graphique interactif en une ligne : survole les points, zoome, clique sur la légende pour masquer une série.

```python
import plotly.express as px

fig = px.bar(tableau, x="colonne_x", y="colonne_y", color="colonne_couleur", title="Mon titre")
fig.show()
```

**Aide-mémoire**

| Graphique | Fonction | Pour montrer |
|---|---|---|
| Histogramme | `px.histogram(df, x=…, nbins=…)` | la distribution d'une variable numérique |
| Barres | `px.bar(tableau, x=…, y=…)` | une valeur par catégorie |
| Barres groupées | `px.bar(…, color=…, barmode="group")` | une valeur par catégorie et sous-catégorie |
| Nuage de points | `px.scatter(tableau, x=…, y=…, color=…, size=…)` | le lien entre deux variables numériques |
| Courbe | `px.line(tableau, x=…, y=…, markers=True)` | une évolution dans le temps |
| Boîte à moustaches | `px.box(df, x=…, y=…)` | comparer des distributions |

Options communes : `title="…"`, `labels={"colonne": "Libellé affiché"}`, `hover_data=["colonne"]`.

⚠️ Plotly attend un **DataFrame avec des colonnes**. Après un `groupby`, pense à `.reset_index()`.

### Exercice 6.1 — Histogramme : la distribution des montants

Importe `plotly.express` sous l'alias `px`, puis trace l'histogramme de la colonne `montant` avec 50 barres. Donne-lui un titre.

Que remarques-tu sur la forme de la distribution ?

In [61]:
import plotly.express as px

px.histogram(df, x="montant", nbins=50, title="Distribution des montants dépensés")

### Exercice 6.2 — Barres : le chiffre d'affaires par catégorie

Trace le chiffre d'affaires par catégorie, barres triées de la plus grande à la plus petite.

Étapes : `groupby` → `sum` → `reset_index()` → `sort_values` → `px.bar`.

In [62]:
px.bar(df.groupby("categorie")["montant"].sum().sort_values(ascending=False))

### Exercice 6.3 — Barres groupées : catégorie × canal

Trace le chiffre d'affaires par catégorie, avec une barre par canal (`color="canal"`, `barmode="group"`).

Essaie ensuite de retirer `barmode="group"` : que se passe-t-il ?

In [63]:
agg = df.groupby(["categorie", "canal"])["montant"].sum().sort_values(ascending=False).reset_index()

In [64]:
px.bar(data_frame=agg, x="categorie", y="montant", color="canal", barmode="group")

In [65]:
px.bar(data_frame=agg, x="categorie", y="montant", color="canal")

### Exercice 6.4 — Courbe : le chiffre d'affaires mensuel

Trace l'évolution du chiffre d'affaires mois par mois, avec des marqueurs sur les points.

In [66]:
agg = df.groupby("mois")["montant"].sum().reset_index()
px.line(agg, x="mois", y="montant", markers=True)

### Exercice 6.5 — Nuage de points : le profil des clients

On change d'échelle : un point = un **client**.

1. Construis un tableau `clients` avec, par `client_id` : `nb_commandes`, `depense_totale`, `panier_moyen`, et `ville` (avec l'agrégation `"first"`, puisqu'un client n'a qu'une ville).
2. Trace `nb_commandes` en abscisse, `depense_totale` en ordonnée, la couleur selon la `ville`, et affiche le `client_id` au survol (`hover_name`).

Repères-tu des clients qui sortent du lot ?

In [73]:
clients = (
    df.groupby("client_id")
    .agg(
        nb_commandes=("commande_id", "count"),
        depense_totale=("montant", "sum"),
        panier_moyen=("montant", "mean"),
        ville=("ville", "first"),
    )
    .round(2)
    .reset_index()
)

px.scatter(
    clients,
    x="nb_commandes",
    y="depense_totale",
    color="ville",
    hover_name="client_id",
    hover_data=["panier_moyen"],
    title="Profil des clients : fréquence d'achat et dépense totale",
    labels={"nb_commandes": "Nombre de commandes", "depense_totale": "Dépense totale (€)", "ville": "Ville"},
)

### Exercice 6.6 — Nuage de points : délai et satisfaction

Reprends le tableau de l'exercice 5.8 (note moyenne par délai de livraison) et trace-le en nuage de points : délai en abscisse, note moyenne en ordonnée, et **taille du point** proportionnelle au nombre de commandes (`size`).

La taille permet de voir d'un coup d'œil quels points reposent sur peu de données.

In [72]:
delai_note = (
    df.groupby("delai_livraison_jours")
    .agg(nb_commandes=("commande_id", "count"), note_moyenne=("note_client", "mean"))
    .reset_index()
)

px.scatter(
    delai_note,
    x="delai_livraison_jours",
    y="note_moyenne",
    size="nb_commandes",
    title="Plus la livraison est longue, plus la note baisse",
    labels={
        "delai_livraison_jours": "Délai de livraison (jours)",
        "note_moyenne": "Note moyenne (sur 5)",
        "nb_commandes": "Nombre de commandes",
    },
)

### Exercice 6.7 — Boîtes à moustaches : les montants par catégorie

Compare la distribution des montants entre catégories avec `px.box`.

💡 Les montants sont très étalés : ajoute `log_y=True` pour passer l'axe vertical en échelle logarithmique et compare la lisibilité.

In [71]:
px.box(
    df,
    x="categorie",
    y="montant",
    log_y=True,
    title="Distribution des montants par catégorie (échelle logarithmique)",
    labels={"categorie": "Catégorie", "montant": "Montant de la commande (€)"},
)

---
# Partie 7 — Mini-étude : à toi de jouer

Plus d'indications pas à pas : la direction pose quatre questions, à toi de choisir les outils. Pour chacune, écris une phrase de conclusion en commentaire.

### Question 1

Quel est le jour de la semaine où l'on enregistre le plus de commandes ? Et celui qui rapporte le plus ?

In [74]:
par_jour = (
    df.groupby("jour_semaine")
    .agg(nb_commandes=("commande_id", "count"), ca=("montant", "sum"))
    .round(0)
    .sort_values("nb_commandes", ascending=False)
)
print("Le plus de commandes :", par_jour["nb_commandes"].idxmax())
print("Le plus de chiffre d'affaires :", par_jour["ca"].idxmax())
par_jour

Le plus de commandes : Friday
Le plus de chiffre d'affaires : Wednesday

              nb_commandes       ca
jour_semaine
Friday                 157  16282.0
Tuesday                151  17279.0
Monday                 145  19363.0
Sunday                 141  17394.0
Thursday               139  15978.0
Wednesday              136  19795.0
Saturday               131  16153.0

### Question 2

Les différentes tranches d'âge utilisent-elles les mêmes canaux ? Montre-le avec un graphique.

In [75]:
age_canal = df.groupby(["tranche_age", "canal"])["commande_id"].count().reset_index(name="nb_commandes")

px.bar(
    age_canal,
    x="tranche_age",
    y="nb_commandes",
    color="canal",
    barmode="group",
    title="Canal d'achat selon la tranche d'âge",
    labels={"tranche_age": "Tranche d'âge", "nb_commandes": "Nombre de commandes", "canal": "Canal"},
)

### Question 3

Les clients mécontents retournent-ils davantage leurs produits ? Utilise la colonne `satisfaction`.

In [76]:
(
    df.groupby("satisfaction")
    .agg(nb_commandes=("commande_id", "count"), taux_retour_pct=("retour", lambda s: s.mean() * 100))
    .round(1)
    .sort_values("taux_retour_pct", ascending=False)
)

              nb_commandes  taux_retour_pct
satisfaction
Mécontent               14             42.9
Sans avis               84             13.1
Neutre                 142             12.7
Satisfait              760             10.0

### Question 4

La direction veut une seule image pour sa réunion : le **taux de retour par catégorie**, en barres triées. Soigne le titre et les libellés.

In [77]:
taux_retour = (df.groupby("categorie")["retour"].mean() * 100).round(1).reset_index(name="taux_retour")
taux_retour = taux_retour.sort_values("taux_retour", ascending=False)

px.bar(
    taux_retour,
    x="categorie",
    y="taux_retour",
    text="taux_retour",
    title="La Mode concentre les retours produits",
    labels={"categorie": "Catégorie", "taux_retour": "Taux de retour (%)"},
)